### ISSUE TITLE
Problem compiling after adding Ngx-Gallery

### ISSUE THREAD

**Issue by webbwangatgmaildotcom** [TryCatchLearn/DatingApp30#4]
Following your instruction here:

'npm install ngx-gallery --save'

add NgxGalleryModule to 'app.module.ts'

wire up compenent.ts/html

'ng serve' shows the following

    ERROR in node_modules/ngx-gallery/ngx-gallery-helper.service.d.ts:1:22 - error TS2724: Module '"../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
    
    1 import { ElementRef, Renderer } from '@angular/core';
                           ~~~~~~~~
    
      node_modules/@angular/core/core.d.ts:5701:31
        5701 export declare abstract class Renderer2 {
                                           ~~~~~~~~~
        'Renderer2' is declared here.
    node_modules/ngx-gallery/ngx-gallery-preview.component.d.ts:1:89 - error TS2724: Module '"../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?
    
    1 import { ChangeDetectorRef, EventEmitter, OnInit, OnChanges, SimpleChanges, ElementRef, Renderer } from '@angular/core';
                                                                                              ~~~~~~~~
    
      node_modules/@angular/core/core.d.ts:5701:31
        5701 export declare abstract class Renderer2 {
                                           ~~~~~~~~~
        'Renderer2' is declared here.

**Comment by webbwangatgmaildotcom** [comment]
i posted this issue about 3 days ago... so far, so help yet... with the above problem, basically I have no gallery rendered in the web page for the gallery component.
Any help is appreciated!

**Comment by tayabur-masud** [comment]
You can try `ngx-gallery-9`

https://www.npmjs.com/package/ngx-gallery-9

**Comment by webbwangatgmaildotcom** [comment]
it is fixed!  thank you!
